### ISSUE TITLE
Nil dereference at Logout after SIGTERM

### ISSUE THREAD

**Issue by dvalter** [emersion/hydroxide#83]
IMAP server sometimes panics with nil pointer dereference after receiving SIGTERM:
```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7a8fde]
goroutine 88 [running]:
github.com/emersion/hydroxide/imap.(*user).Logout(0xc000120380, 0xc00048e000, 0x870720)
        /tmp/trizen-dvalter/hydroxide-git/src/hydroxide/imap/user.go:216 +0x4e
github.com/emersion/go-imap/server.(*conn).Close(0xc00012c6c0, 0xc0002bc120, 0xc000084300)
        /home/dvalter/.local/gopath/pkg/mod/github.com/emersion/go-imap@v1.0.3/server/conn.go:159 +0x6f
github.com/emersion/go-imap/server.(*Server).serveConn.func1(0xc0000bc2c0, 0x94eb00, 0xc00012c6c0)
        /home/dvalter/.local/gopath/pkg/mod/github.com/emersion/go-imap@v1.0.3/server/server.go:277 +0x7e
github.com/emersion/go-imap/server.(*Server).serveConn(0xc0000bc2c0, 0x94eb00, 0xc00012c6c0, 0x0, 0x0)
        /home/dvalter/.local/gopath/pkg/mod/github.com/emersion/go-imap@v1.0.3/server/server.go:281 +0x13c
created by github.com/emersion/go-imap/server.(*Server).Serve
        /home/dvalter/.local/gopath/pkg/mod/github.com/emersion/go-imap@v1.0.3/server/server.go:229 +0x20e
```

Probably related to #82 because an all known cases it happened after client had sent `IMAP LOGOUT`

**Comment by emersion** [comment]
Can you try 5cd1c7a9211f and see whether it fixes this issue?
